#!/bin/bash

# Do not edit this file!

echo "Loading startup.sh..."
bash /home/startup.sh

echo "Creating config.json..."
cd /home/shell-bot
cat > config.json <<EOF
{
    "authToken": "$BOT_TOKEN",
    "owner": $OWN_ID
}
EOF
echo "Done."

echo "Starting Bot..."
node server
